# Generated by Django 5.2.17 on 2026-10-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interests', '0002_profileinterest_and_more'),
        ('profiles', '0002_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='interests',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='interests.profileinterest'),
        ),
    ]
