# Generated by Django 5.2.17 on 2026-10-02 16:37

from django.db import migrations, models


def seed_profile_interests(apps, schema_editor):
    ProfileInterest = apps.get_model('interests', 'ProfileInterest')
    initial_interests = (
        ('Travel', 'travel'), ('Music', 'music'), ('Movies', 'movies'),
        ('Hiking', 'hiking'), ('Fitness', 'fitness'), ('Food', 'food'),
        ('Photography', 'photography'), ('Reading', 'reading'), ('Gaming', 'gaming'),
    )
    ProfileInterest.objects.using(schema_editor.connection.alias).bulk_create(
        [ProfileInterest(name=name, slug=slug) for name, slug in initial_interests],
        ignore_conflicts=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('interests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=90, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name', 'id'),
            },
        ),
        migrations.RunPython(seed_profile_interests, migrations.RunPython.noop),
        migrations.RenameIndex(
            model_name='interest',
            new_name='interests_i_from_us_e8b5dd_idx',
            old_name='interests_i_from_us_aa10d3_idx',
        ),
        migrations.RenameIndex(
            model_name='interest',
            new_name='interests_i_to_user_771018_idx',
            old_name='interests_i_to_user_2755eb_idx',
        ),
    ]
