# Generated by Django 5.2.17 on 2026-10-02 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='match',
            new_name='matches_mat_user_on_733b02_idx',
            old_name='matches_mat_user_on_b31334_idx',
        ),
        migrations.RenameIndex(
            model_name='match',
            new_name='matches_mat_user_tw_e621df_idx',
            old_name='matches_mat_user_tw_9dfaba_idx',
        ),
    ]
